language: python
python:
    - 3.5
    - 3.6

install:
    - pip install -r requirements.txt

script:
    - pylint HWL3.py
    - pylint HWL4/tests.py
    - pylint HWL4/wsgi.py
    - pylint HWL4/parse.py

sudo: false
