language: python
python:
    - 3.5
    - 3.6

install:
    - pip install -r requirements.txt

script:
    - pylint HWL3
    - pylint HWL4/tests
    - pylint HWL4/wsgi
    - pylint HWL4/parse

sudo: false
