# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import task.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready_time', models.DateTimeField(auto_now=True)),
                ('scores', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('estimate', models.DateTimeField(default=django.utils.timezone.now, validators=[task.models.datetime_validate])),
                ('creating_time', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(choices=[(1, 'ready'), (0, 'in_progress')], default=0, verbose_name='Состояние задачи: ')),
                ('roadmap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadmap.Roadmap')),
            ],
        ),
        migrations.AddField(
            model_name='scores',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
    ]
