# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('estimate', models.DateTimeField(auto_now=True, validators=[task.models.datetime_validate])),
                ('Завершено?', models.BooleanField(default=False)),
            ],
        ),
    ]
