# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creating_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
