# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 10:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_time_of_creating',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 14, 10, 1, 55, 408467), validators=[task.models.datetime_validate]),
        ),
    ]
