# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
        ('task', '0006_auto_20170514_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='roadmap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadmap.Roadmap'),
        ),
    ]
