# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_task_roadmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Завершено?',
            field=models.BooleanField(default=True),
        ),
    ]
