# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 07:55
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20170523_1904'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('free_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
