# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20170524_0755'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
            ],
        ),
    ]
